### ISSUE TITLE
Deleted column from parent CT created with provisioning

### ISSUE THREAD

**Issue by SuleymanA** [OfficeDev/PnP-Sites-Core#283] opened 2016-01-04 14:34 UTC
Hi,

After performing a full site provisioning I noticed that my content type that inherits from a OOB content type are still having the column that was deleted. To clarity:
- I have a site content type which inherits from the 2013 workflow task content type
- I removed the "Task outcome" column (which was inherited from the parent CT) and added a new outcome column with specific outcomes
- The provisioning template, which is also created using the PnP Provisioning Framework, only has the new outcome column. "Task outcome" column is not in the FieldRefs of the custom content type.
- Result after provisioning is that both my new outcome column and "Task outcome" column are present in the by provisioning framework created site content type.

Kind regards,
Suleyman

**Comment by PaoloPia** [comment] 2016-02-21 23:03
Hi,
Thanks for your feedback. By design we do not remove artifacts, when applying a provisioning template. Thus, what you see is the intended behavior. I'm sorry, but I will close this request.

**Closed by PaoloPia** 2016-02-21 23:03 UTC
