### ISSUE TITLE
Exporting web parts is failing

### ISSUE THREAD

**Issue by PieterVeenstra** [OfficeDev/PnP-Sites-Core#329] opened 2016-02-02 17:02 UTC
I'm trying this in  the dev branch.
exporting web parts doesn't seem to 100% work yet. The {site} is also used to close tags like: {site}> 

This results in : Name cannot begin with the '{' character, hexadecimal value 0x7B. Line 4, position 166."

An examples of the web part contents that I picked up:

"<  webParts>\r\n  < webPart xmlns=\"http:{site}{site}schemas.microsoft.com{site}WebPart{site}v3\">\r\n    <  metaData>\r\n      < type name=\"Microsoft.SharePoint.WebPartPages.GettingStartedWebPart, Microsoft.SharePoint, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c\"{site}>\r\n
      <  importErrorMessage >Cannot import this Web Part.<  {site}importErrorMessage>\r\n    < {site}metaData>\r\n    < data>\r\n      <  properties>\r\n        <  property name=\"AllowZoneChange\" type=\"bool\">True< {site}property>\r\n        < property name=\"HelpUrl\" type=\"string\" {site}>\r\n        < property name=\"Hidden\" type=\"bool\">False< {site}property>\r\n        < property name=\"MissingAssembly\" type=\"string\">Cannot import this Web Part.< {site}property>\r\n        < property name=\"Description\" type=\"string\" {site}>\r\n        < property name=\"BaseViewID\" type=\"string\">2< {site}property>\r\n        < property name=\"AllowHide\" type=\"bool\">True< {site}property>\r\n        < property name=\"AllowMinimize\" type=\"bool\">True< {site}property>\r\n        < property name=\"Title\" type=\"string\">Get started with your site< {site}property>\r\n        < property name=\"TitleUrl\" type=\"string\" {site}>\r\n        < property name=\"ExportMode\" type=\"exportmode\">All< {site}property>\r\n        < property name=\"ChromeType\" type=\"chrometype\">None< {site}property>\r\n        < property name=\"AllowConnect\" type=\"bool\">True< {site}property>\r\n        < property name=\"Width\" type=\"string\" {site}>\r\n        < property name=\"Height\" type=\"string\" {site}>\r\n        < property name=\"CatalogIconImageUrl\" type=\"string\" {site}>\r\n        < property name=\"HelpMode\" type=\"helpmode\">Modeless< {site}property>\r\n        < property name=\"AllowEdit\" type=\"bool\">True< {site}property>\r\n        < property name=\"TitleIconImageUrl\" type=\"string\" {site}>\r\n        < property name=\"Direction\" type=\"direction\">NotSet< {site}property>\r\n        < property name=\"AllowClose\" type=\"bool\">True< {site}property>\r\n        < property name=\"ChromeState\" type=\"chromestate\">Normal< {site}property>\r\n      < {site}properties>\r\n    < {site}data>\r\n  < {site}webPart>\r\n< {site}webParts>"

**Comment by arangas** [comment] 2016-02-09 00:32
I hit this as well and cannot use the 201512 formatter as a result. The [line that fails is here](https://github.com/OfficeDev/PnP-Sites-Core/blob/a21e3680104f8be040e6401513f809b444b0baaf/Core/OfficeDevPnP.Core/Framework/Provisioning/Providers/Xml/XMLPnPSchemaV201512Formatter.cs#L714). It assumes web part contents will contain valid XML by using XElement.Parse(), but a web part such as "Get started with Apps for Office and SharePoint" that comes from the app site template uses the invalid form you've provided.

The 201508 formatter works fine because that version makes no attempt to parse the web part contents as valid XML. I'm not sure of a way to workaround this but to revert to this behaviour or provide two properties - one with the raw web part contents, and the order with valid XML where it exists.

Is there anything gained by parsing the XML?

**Comment by jansenbe** [comment] 2016-02-09 05:48
Did you try this with the latest released version. We actually did change this yesterday afternoon...

**Comment by arangas** [comment] 2016-02-09 06:17
The version I used was from NuGet: OfficeDevPnPCore16 2.1.1602.0. Is there a newer version coming down the pipes @jansenbe ?

**Comment by jansenbe** [comment] 2016-02-09 06:53
hmmm...that' the latest version. We fixed an issue where the CDATA tags that SharePoint emitted were tokenized as {cdatastart} and {cdataend}...resulting in an XML parser error. Can you past the web part XML that fails?

**Comment by PaoloPia** [comment] 2016-02-09 08:50
Hi @PieterVeenstra, how did you get the XML that you put in your message? Did you simply exported a site template? Was it a root site of a web application? I mean something like https://tenant.sharepoint.com/ ?

**Comment by PieterVeenstra** [comment] 2016-02-09 08:54
Hi @PaoloPia.
I created a new tenant (this then creates the default https://tenant.sharepoint.com/ site collection). Then I exported the root site using PowerShell and then the web part was there.

**Comment by PaoloPia** [comment] 2016-02-09 08:57
Ok, thanks! I think we've got the issue ... we will fix it :).

**Comment by erwinvanhunen** [comment] 2016-02-09 09:47
I just merged a possible fix for this issue, but it requires more testing.

**Comment by VesaJuvonen** [comment] 2016-02-09 12:59
Tested this with root site extraction to sub site creation and works as expected now with the new fix. We'll get this updated on the new release coming still this week. 

@PieterVeenstra @arangas - Can you confirm that you can reproduce this only if you extract from root and try to apply to sub sites... not if you do sub site to sub site? - Just to ensure that we are properly fixing this, since could not reproduce the issue with sub site to sub site model. thx.

Did find small other issues on the root site extraction, which we consider as an exception, but good to get that supported in the engine as well, to avoid reports.

**Comment by PieterVeenstra** [comment] 2016-02-09 13:07
Hi @VesaJuvonen,

Yes this was only an issue when exporting/importing from a rootsite to a subsite.

**Comment by arangas** [comment] 2016-02-09 23:51
@VesaJuvonen I had this problem exporting a root site (created using the App/Developer template) and didn't get to importing. Unless I'm missing something this issue is specific to exporting web parts and is independent of whether it's a root site or sub site.

By the way, I got the same XML-like output as @PieterVeenstra by debugging the PnP code directly and checking the variable storing the web part's contents (see link to code in my previous comment).

Thanks for being so quick to look at this and hope it will be fixed soon!

**Comment by VesaJuvonen** [comment] 2016-02-11 16:36
Thx for the input. We cannot reproduce this issue when performing export from sub site collection and then applying to sub site collection. It could be reproduced only when exporting from root site and then applying template to sub site collection. Exporting from root site collection is typically an exception, but we obviously want to ensure that this will work as well, if used.

Fix has been applied to dev branch and we are looking to do a updated Nuget package early next week.

**Closed** 2016-02-12 14:00 UTC
