### ISSUE TITLE
List and RelationshipBehavior are removed when creating list-only lookup fields

### ISSUE THREAD

**Issue by lanegoolsby** [OfficeDev/PnP-Sites-Core#180] opened 2015-11-11 23:58 UTC
If the engine is creating a list instance lookup column that doesn't exist, in ObjectListInstance/CreateField the call to PrepareField removes the List ID (and the Relationship Behavior) but the List ID is never added back. If I comment out the line to PrepareField() the issue goes away and the field is added as expected. I don't mind issuing a PR with the PrepareField commented out, but it seems someone wrote this function for a reason and I must confess to not fully understanding the reason for it (both attributes are respected and work as expected in my case so there must be some edge case its for...).

**Comment by SchauDK** [comment] 2015-11-12 06:48
Sorry to hear that you're having problems with it. The reason for temporarily removing List ID is that all lists and fields must exist before the lookup field can be properly created. I created the PrepareField() function because additional attributes needed to be removed (because of Relationship Behaviour), otherwise ShaerPoint will not accept the SchemaXml. 
 The ObjectLookupFields should be able to handle both "Lists/Yadda" and tokens. 
 Could you please provide med with the pnp:Field XML. Meanwhile, I'll try to reproduce your scenario.

**Comment by SchauDK** [comment] 2015-11-12 11:16
Unfortunately I haven't been able to reproduce the issue. I've tried both cases (Lists/Yadda and token) and the Lookup field is created just fine.

**Comment by lanegoolsby** [comment] 2015-11-12 12:20
Thanks for your help on this Michael.

Can you point me to where in the code the list binding is re-added? I think this is the root of the issue, that code either isn't being called or isn't in master. I don't see the PrepareField method storing/caching the list binding information for later processing, nor do I see a post-processing method to come back later and fix the bindings, but this may be my own unfamiliarity with the code. In my case the field gets created but the binding information is not present (when you look at the field in List Settings the lookup Target List and Show Field are blank). I have many lookup fields, this is pretty consistent across all of them, but one example FieldXML is as follows:

<Field Type="Lookup" DisplayName="Step" Required="FALSE" EnforceUniqueValues="FALSE" List="{listid:Steps}" ShowField="Display" UnlimitedLengthInDocumentLibrary="FALSE" RelationshipDeleteBehavior="None" ID="{d65fcf15-e790-445f-8afb-77e59b77aa28}" SourceID="{213539BC-558E-4851-AAEB-31510BE1A2CC}" StaticName="Step" Name="Step" ColName="int1" RowOrdinal="0" />

This is a straight export from the GetProvisioningTemplate, I have not edited it any way.

**Comment by SchauDK** [comment] 2015-11-12 13:10
I've just provisioned your field (just pointing at another list), so there's nothing wrong with the FieldXML. 

Take a look at ObjectLookupFields.ProcessLookupFields
First it is processing SiteColumns, then ListColumns. 

            foreach (var listInstance in template.Lists)
            {
                foreach (var listField in listInstance.Fields)
                {
                    var fieldElement = XElement.Parse(listField.SchemaXml);
                    if (fieldElement.Attribute("List") == null) continue;

                    var fieldId = Guid.Parse(fieldElement.Attribute("ID").Value);
                    var listIdentifier = parser.ParseString(fieldElement.Attribute("List").Value);
                    var relationshipDeleteBehavior = fieldElement.Attribute("RelationshipDeleteBehavior") != null ? fieldElement.Attribute("RelationshipDeleteBehavior").Value : string.Empty;
                    var webId = string.Empty;

                    var listUrl = UrlUtility.Combine(web.ServerRelativeUrl, parser.ParseString(listInstance.Url));

                    var createdList = web.Lists.FirstOrDefault(l => l.RootFolder.ServerRelativeUrl.Equals(listUrl, StringComparison.OrdinalIgnoreCase));
                    if (createdList != null)
                    {
                        var field = createdList.Fields.GetById(fieldId);
                        web.Context.Load(field, f => f.SchemaXml);
                        web.Context.ExecuteQueryRetry();

                        List sourceList = FindSourceList(listIdentifier, web, rootWeb);

                        if (sourceList != null)
                        {
                            web.Context.Load(sourceList.ParentWeb);
                            web.Context.ExecuteQueryRetry();

                            webId = sourceList.ParentWeb.Id.ToString();
                            ProcessField(field, sourceList.Id, webId, relationshipDeleteBehavior);
                        }
                    }
                }
            }

Maybe the problem is this
    webId = sourceList.ParentWeb.Id.ToString();

The ParentWeb is not explicit loaded, but in may case it is available. Maybe it isn't available in your case. Do you have the possibility to debug it?

**Comment by lanegoolsby** [comment] 2015-11-12 13:41
OK, I see one problem. This line:

    List sourceList = FindSourceList(listIdentifier, web, rootWeb)

Returns null even though the lookup target list does in fact exist. I am still looking at it but I suspect the fact that my lists are in a sub web may be in play.

**Comment by lanegoolsby** [comment] 2015-11-12 13:49
Yeah, this bit:

        private static List FindSourceList(string listIdentifier, Web web, Web rootWeb)
        {
            Guid listGuid = Guid.Empty;

            if (!Guid.TryParse(listIdentifier, out listGuid))
            {
                var sourceListUrl = UrlUtility.Combine(web.ServerRelativeUrl, listIdentifier);
                return web.Lists.FirstOrDefault(l => l.RootFolder.ServerRelativeUrl.Equals(sourceListUrl, StringComparison.OrdinalIgnoreCase));
            }
            else
                return rootWeb.Lists.FirstOrDefault(l => l.Id.Equals(listGuid));
        }

Never checks the sub web so it returns null.

**Comment by SchauDK** [comment] 2015-11-12 14:26
Ahh ok.
While you're at it. Could you log an Warning or Error using PnPMonitoredScope, if the list isn't found.

**Comment by lanegoolsby** [comment] 2015-11-12 14:36
Yep

**Comment by PaoloPia** [comment] 2016-02-21 18:15
Hi,
Thanks for your feedback. I'm wondering if this issue is still to be considered open, based on the fact that we updated the engine a lot during the last months. If you confirm that it is still open ... we will try to figure it out and fix any possible bug. Otherwise I will close it. Thanks.

**Comment by lanegoolsby** [comment] 2016-02-22 21:47
Hi Paola, the issue has been fixed for me for a while. I issued PR #191 some time ago to fix the issue that I was running into.

**Comment by PaoloPia** [comment] 2016-02-22 22:27
Ok, great! I will close this one. Thanks.

**Closed by PaoloPia** 2016-02-22 22:27 UTC
