### ISSUE TITLE
App.config missing from Core/OfficeDevPnP.Core.Tests

### ISSUE THREAD

**Issue by andreashebeisen** [OfficeDev/PnP-Sites-Core#654] opened 2016-06-30 19:21 UTC
#### Category
[X] Bug
[ ] Enhancement

#### Environment
[X] Office 365 / SharePoint Online
[X] SharePoint 2016
[X] SharePoint 2013

#### Expected or Desired Behavior
After the initial clone the solution should build without any errors.

#### Observed Behavior
After the initial clone I get a build error because of a missing App.config file in OfficeDevPnP.Core.Tests which reads:
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not copy the file "App.config" because it was not found.	OfficeDevPnP.Core.Tests

The App.config is part of the project but missing on disk and in the repository under https://github.com/OfficeDev/PnP-Sites-Core/tree/master/Core/OfficeDevPnP.Core.Tests (only App.config.sample is present.

#### Steps to Reproduce
Do a fresh clone to a new repository location. Open the solution and build it. Simple workaround by copying App.config.sample to a new file App.config.
Thx in advance.

**Comment by erwinvanhunen** [comment] 2016-09-07 15:59
This is by design. We explicitly exclude the app.config to prevent accidental commits containing the app.config which might contain usernames and/or passwords. The steps you take (copy app.config.sample to app.config) is the right way forward. I will close this issue.

**Closed by erwinvanhunen** 2016-09-07 15:59 UTC
