### ISSUE TITLE
TimeZone always overridden by template

### ISSUE THREAD

**Issue by LenCardinal** [OfficeDev/PnP-Sites-Core#395] opened 2016-02-18 13:16 UTC
In building a provisioning system, the time zone is specified when the site is created.  The provisioning template also has a "TimeZone" attribute, which seems to always override the site's time zone.

I tried removing the XML's TimeZone attribute, but this resulted in "Value cannot be null" exception.

**Comment by PaoloPia** [comment] 2016-02-21 23:56
Hi Len,
Thanks for your feedback. Are you experiencing the issue on-prem on in SharePoint Online? I cannot reproduce it in SPO. Thanks.

**Comment by LenCardinal** [comment] 2016-02-22 14:09
SharePoint Online

**Comment by PaoloPia** [comment] 2016-02-22 14:15
Ok, thank you. Can you try it again and/or provide a use case to reproduce the issue? I tried it multiple times, but I wasn't able to reproduce it. Thanks.

**Comment by LenCardinal** [comment] 2016-02-22 14:20
So "TimeZone" does not overwrite the site's TimeZone in your tests?

**Comment by PaoloPia** [comment] 2016-02-22 14:29
If I set a specific timezone with the template, it is overwritten. If I don't it doesn't.

**Comment by LenCardinal** [comment] 2016-02-22 14:33
to not set a specific timezon, should the TimeZone= attribute be deleted?  Or empty quotes?

**Comment by PaoloPia** [comment] 2016-02-22 15:48
Put it to 0. Please, test and let me know. Thanks.

**Comment by LenCardinal** [comment] 2016-02-22 15:48
Hi Paolo:

If I set TimeZone="", the schema validation fails, and ApplyProvisionig template throws an exception saying that the XML was invalid.

If I remove TimeZone= altogether, the schema is valid, but : Exception: Value cannot be null. exception

Just saw your response...will try it now.

**Comment by LenCardinal** [comment] 2016-02-22 15:54
"0" works. Thanks. FYI, the 2015-12-05 schema I have lists the attribute as optional, though omitting the attribute from the XML seems to result in an exception "Value cannot be null"
    <xsd:attribute name="TimeZone" type="pnp:ReplaceableInt" use="optional">
      <xsd:annotation>
        <xsd:documentation xml:lang="en">
          The Time Zone that is used on the server, optinal attribute.
        </xsd:documentation>
      </xsd:annotation>
    </xsd:attribute>

Stack trace:
at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo 
info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at OfficeDevPnP.Core.Framework.Provisioning.Providers.Xml.XMLPnPSchemaV201512Formatter.ToProvisioningTemplate(Stream template, String identifier)
   at OfficeDevPnP.Core.Framework.Provisioning.Providers.Xml.XMLPnPSchemaFormatter.ToProvisioningTemplate(Stream template, String identifier)
   at OfficeDevPnP.Core.Framework.Provisioning.Providers.Xml.XMLTemplateProvider.GetTemplate(String uri, String identifier, ITemplateFormatter formatter)
   at OfficeDevPnP.PowerShell.Commands.Branding.ApplyProvisioningTemplate.ExecuteCmdlet()
   at OfficeDevPnP.PowerShell.Commands.SPOCmdlet.ProcessRecord()
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException

**Comment by PaoloPia** [comment] 2016-02-22 15:55
Ok, thank you. Please, if you can, update the schema to the latest. We also do provide a Convert-SPOProvisioningTemplate cmdlet for this purpose. I will close this issue, in the meantime.

**Closed by PaoloPia** 2016-02-22 15:55 UTC
