### ISSUE TITLE
[Provisioning Engine]: ProvisioningTemplateFile 

### ISSUE THREAD

**Issue by domedellolio** [OfficeDev/PnP-Sites-Core#611] opened 2016-06-08 14:55 UTC
It seems that ProvisioningTemplateFile is ignored by the provisioning engine.
And I get this error if **Templates** node contains just 1 occurence of  **ProvisioningTemplateFile**

ERROR:
====
Apply-SPOProvisioningTemplate : Value cannot be null.
Parameter name: source

**Comment by PaoloPia** [comment] 2016-06-09 12:39
Hi,
In the provisioning engine we only support the ProvisioningTemplate element, and its children. The ProvisioningTemplateFile is defined at schema level only. I will close this issue. Thanks for using the PnP Provisioning Engine.

**Closed by PaoloPia** 2016-06-09 12:39 UTC

**Comment by DeChrist** [comment] 2016-07-18 14:25
I ran into the same issue. This is confusing to say the least. 
Is there a reason why it remains in the schema and is not supported in the engine?
Furthermore some of the latest samples use that feature (see [ProvisioningSchema-2016-05-FullSample-02.xml](https://github.com/OfficeDev/PnP-Provisioning-Schema/blob/master/Samples/ProvisioningSchema-2016-05-FullSample-02.xml#L24)).
This should at least be documented in the "Current implemented version (in the PnP Provisioning Engine)" [here](https://github.com/OfficeDev/PnP-Provisioning-Schema/blob/master/ProvisioningSchema-2015-12.md#provisioningtemplatefile).

**Comment by ruslanurban** [comment] 2017-01-16 22:24
I just spent over an hour trying to figure out what the problem is. The sample files are confusing! 

Please, add a more descriptive message indicating that the `ProvisioningTemplateFile` functionality has not been implemented yet and update schema documentation.
