### ISSUE TITLE
Version settings not provisioned from template

### ISSUE THREAD

**Issue by konraplo** [OfficeDev/PnP-Sites-Core#686] opened 2016-07-27 15:06 UTC
Hi

If try to provision versioning settings into my List/DocLibrary it doesn't work. Parameters like MinorVersionLimit and MaxVersionLimit are ignored and EnableVersioning works only if the list is created - so I can't change EnableVersioning = false/true for existing lists.

•PnP Sites Core - https://github.com/OfficeDev/PnP-Sites-Core 

Category

[x ] Bug
 [ ] Enhancement

Environment

[ ] Office 365 / SharePoint Online
 [ ] SharePoint 2016
 [ x] SharePoint 2013

Expected or Desired Behavior

After provision a template number of versions/drafts should be provisioned for corresponding List.

Observed Behavior

After provision a template number of versions/drafts, versioning enabled are not being provisioned from template.

Steps to Reproduce

Create and provision a template with EnableVersioning=true, MaxVersionLimit=20 for List/DocLib. Try to change this settings using provisioning template.

KR
Konrad

**Comment by PaoloPia** [comment] 2016-07-27 15:37
Hi,
Have you tried it using the DEV branch or the current MASTER release?

**Comment by konraplo** [comment] 2016-07-27 15:59
dev

**Comment by erwinvanhunen** [comment] 2016-09-08 15:19
I just checked with the latest dev release and I'm not able to reproduce this issue anymore. I will close this issue, but do no hesitate to reopen it if applicable.

**Closed by erwinvanhunen** 2016-09-08 15:19 UTC

**Comment by casvaniersel** [comment] 2017-01-09 14:38
Hi I'm experiencing exactly the same issue at the moment running SharePointPnPCore2013 2.9.1611 with ProvisioningSchema 201605. My ListInstance looks like this:

`<pnp:ListInstance Title="Werkdocumenten" Description="" DocumentTemplate="{site}/Werkdocumenten/Forms/template.dotx" TemplateType="101" Url="Werkdocumenten" EnableVersioning="true" EnableMinorVersions="false" MaxVersionLimit="5" TemplateFeatureID="00bfea71-e717-4e80-aa17-d0c71b360101" ContentTypesEnabled="true" EnableAttachments="false">`

Afterwards when I check the library is created as expected and versioning is also enabled, but the versionlimit has not been set. 

Maybe this issue can be reopened? Or should I create a new one?

**Comment by 2toLeadMike** [comment] 2017-03-30 17:41
@casvaniersel I just had the same issue occur. I upgraded from a release from last year to the current one (2.13.1703.0) and simply re-applying the template worked.

**Comment by dfeuerhake** [comment] 2017-08-02 13:50
The MajorVersionLimit attribute is excluded from the creation and update mechanism when templates are applied to websites in SharePoint 2013. Why is that? The attribute is available in SP2013 CSOM since CU Dec 2014 (https://blogs.msdn.microsoft.com/vesku/2014/12/15/latest-api-updates-in-client-side-object-model-dec-2014-cu-for-sp2013/). Just checked this in the most recent version of PnP. Any explanation?

```
#if !SP2013
                    createdList.MajorVersionLimit = list.MaxVersionLimit;
#endif
```
