### ISSUE TITLE
Provisioning template generator: does not include library's Versioning settings

### ISSUE THREAD

**Issue by LenCardinal** [OfficeDev/PnP-Sites-Core#373] opened 2016-02-13 18:59 UTC
The provisioning template generator does not seem to capture library versioning settings.  For a document library where the maximum number of versions was set to 10, resulting XML contains: 
MaxVersionLimit="0"

**Comment by PaoloPia** [comment] 2016-02-22 00:06
Hi,
Thanks for your feedback. Are you working with SharePoint Online or SharePoint on-premises? Thanks.

**Comment by erwinvanhunen** [comment] 2016-09-08 15:21
I just checked against SharePoint Online and am not able to reproduce this issue anymore. I will close this issue, but do not hesitate to reopen it if your feel the issue still applies.

**Closed by erwinvanhunen** 2016-09-08 15:21 UTC
